# Generated by Django 4.0.1 on 2022-01-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employe_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employe_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=30)),
                ('postion', models.CharField(max_length=20)),
            ],
        ),
    ]
