# Generated by Django 4.0.1 on 2022-01-11 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_postion_employe_data_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe_data',
            name='email',
        ),
    ]
