# Generated by Django 4.0.1 on 2022-01-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_employe_data_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe_data',
            name='date_time',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
